// app/index.js
import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, Alert, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy'; // legacy import to avoid warnings
import { StatusBar } from 'expo-status-bar';

const LATE_FEE = 100;
const DUE_DAY = 15; // every month's 20th

export default function Index() {
  const [name, setName] = useState('');
  const [fee, setFee] = useState('');
  const [generating, setGenerating] = useState(false);

  // 🗓 Get next upcoming 20th date (this or next month)
  const getFixedDueDate = () => {
    const today = new Date();
    let dueMonth = today.getMonth();
    let dueYear = today.getFullYear();

    if (today.getDate() > DUE_DAY) {
      dueMonth += 1;
      if (dueMonth > 11) {
        dueMonth = 0;
        dueYear += 1;
      }
    }

    return new Date(dueYear, dueMonth, DUE_DAY);
  };

  const formatDate = (date) => {
    const d = new Date(date);
    return `${String(d.getDate()).padStart(2, '0')}-${String(d.getMonth() + 1).padStart(2, '0')}-${d.getFullYear()}`;
  };

  const isLate = (dueDate) => {
    const today = new Date();
    const todayMid = new Date(today.getFullYear(), today.getMonth(), today.getDate());
    const dueMid = new Date(dueDate.getFullYear(), dueDate.getMonth(), dueDate.getDate());
    return todayMid > dueMid;
  };

  const escapeHtml = (s) =>
    String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;').replace(/'/g, '&#039;');

  const generatePdfAndShare = async () => {
    if (!name.trim()) return Alert.alert('Validation', 'Please enter student name.');
    if (!fee.trim()) return Alert.alert('Validation', 'Please enter tuition fee.');

    try {
      setGenerating(true);

      const feeNum = parseFloat(fee) || 0;
      const dueDate = getFixedDueDate();
      const lateApplied = isLate(dueDate);
      const total = lateApplied ? feeNum + LATE_FEE : feeNum;
      const todayStr = formatDate(new Date());
      const dueStr = formatDate(dueDate);

      const html = `
        <html>
        <head>
          <meta charset="utf-8" />
          <style>
            body { font-family: Arial, Helvetica, sans-serif; background:#f9f9f9; margin:0; padding:24px; }
            .voucher { max-width:700px; margin:auto; background:#fff; border-radius:8px; border:1px solid #ddd; padding:24px; }
            .header { display:flex; justify-content:space-between; align-items:center; }
            .title { font-size:22px; font-weight:bold; color:#d63384; }
            .subtitle { font-size:12px; color:#666; }
            table { width:100%; margin-top:20px; border-collapse:collapse; }
            td { padding:10px 6px; border-bottom:1px solid #eee; }
            .label { font-weight:600; color:#333; }
            .value { text-align:right; }
            .total { font-weight:700; color:#d63384; }
            .footer { text-align:center; font-size:12px; color:#777; margin-top:20px; }
            .note { font-size:12px; color:#444; margin-top:10px; }
          </style>
        </head>
        <body>
          <div class="voucher">
            <div class="header">
              <div>
                <div class="title">Nadia's Tuition Center</div>
                <div class="subtitle">Official Fee Voucher</div>
              </div>
              <div style="text-align:right;">
                <div style="font-weight:600;">Date</div>
                <div class="subtitle">${todayStr}</div>
              </div>
            </div>

            <h3 style="text-align:center; margin-top:20px;">Payment Voucher</h3>

            <table>
              <tr><td class="label">Student Name</td><td class="value">${escapeHtml(name)}</td></tr>
              <tr><td class="label">Tuition Fee</td><td class="value">PKR ${feeNum.toFixed(2)}</td></tr>
              <tr><td class="label">Due Date</td><td class="value">${dueStr}</td></tr>
              <tr><td class="label">Late Fee</td><td class="value">PKR ${LATE_FEE.toFixed(2)}</td></tr>
              <tr><td class="label total">Total Payable</td><td class="value total">PKR ${total.toFixed(2)}</td></tr>
            </table>

            <div class="note">
              ${
                lateApplied
                  ? `Payment received after due date. A late fee of PKR ${LATE_FEE} has been applied.`
                  : `Please pay before ${dueStr} to avoid a late fee of PKR ${LATE_FEE}.`
              }
            </div>

            <div class="footer">Generated by Nadia's Tuition Center Voucher App</div>
          </div>
        </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      const cleanName = name.trim().replace(/\s+/g, '_').replace(/[^\w\-]/g, '');
      const pdfName = `${cleanName}_voucher.pdf`;
      const dest = FileSystem.cacheDirectory + pdfName;
      await FileSystem.moveAsync({ from: uri, to: dest });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(dest, {
          mimeType: 'application/pdf',
          dialogTitle: 'Share Voucher PDF',
        });
      } else {
        Alert.alert('PDF Created', dest);
      }
    } catch (e) {
      Alert.alert('Error', e.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <SafeAreaView style={{ flex: 1, padding: 16, backgroundColor: '#fff' }}>
      <StatusBar style="dark" />
      <ScrollView>
        <Text style={{ fontSize: 22, fontWeight: '700', color: '#d63384', marginBottom: 12 }}>
          Nadia's Tuition Center
        </Text>

        <Text>Student Name</Text>
        <TextInput
          value={name}
          onChangeText={setName}
          placeholder="Enter student name"
          style={{ borderWidth: 1, borderColor: '#ccc', padding: 10, borderRadius: 6, marginTop: 6 }}
        />

        <Text style={{ marginTop: 12 }}>Tuition Fee</Text>
        <TextInput
          value={fee}
          onChangeText={setFee}
          placeholder="0.00"
          keyboardType="numeric"
          style={{ borderWidth: 1, borderColor: '#ccc', padding: 10, borderRadius: 6, marginTop: 6 }}
        />

        <Text style={{ marginTop: 10, color: '#666' }}>
          Due Date: {formatDate(getFixedDueDate())} {'\n'}
          Late Fee: PKR {LATE_FEE}
        </Text>

        <TouchableOpacity
          onPress={generatePdfAndShare}
          disabled={generating}
          style={{
            backgroundColor: '#d63384',
            padding: 14,
            borderRadius: 8,
            marginTop: 20,
          }}
        >
          <Text style={{ color: '#fff', textAlign: 'center', fontWeight: '700' }}>
            {generating ? 'Generating...' : 'Generate & Share Voucher'}
          </Text>
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}
